accelerator: cuda
strategy: auto
devices: 1
precision: 16-mixed

max_epochs: 10
min_epochs: 3
limit_train_batches: null
limit_val_batches: 1000
limit_test_batches: null
limit_predict_batches: null
overfit_batches: 0.0
val_check_interval: 5000
check_val_every_n_epoch: 1
enable_checkpointing: true
enable_progress_bar: false
enable_model_summary: true

default_root_dir: /mnt/projects/debruinz_project/integration

callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      filename: '{epoch}-{val_loss:.2f}'
      save_top_k: 3
      save_last: true
      monitor: val_loss
      mode: min

  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val_loss
      patience: 3
      mode: min
      
logger:
  - class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args: 
      save_dir: ${default_root_dir}/tensorboard
