# lightning.pytorch==2.2.5
class_path: sciml.data.CellxgeneDataModule
init_args:
  batch_size: 64
  obs_query_value_filter: is_primary_data == True and assay in ["microwell-seq",
    "10x 3' v1", "10x 3' v2", "10x 3' v3", "10x 3' transcription profiling", "10x
    5' transcription profiling", "10x 5' v1", "10x 5' v2"]
  obs_column_names:
  - dataset_id
  - assay
  - donor_id
  weights:
    train: 0.8
    test: 0.15
    val: 0.05
  soma_chunk_size: 1000
  num_workers: 3