# lightning.pytorch==2.2.5
class_path: sciml.VAE
init_args:
  encoder_layers:
  - 60664
  - 1024
  - 512
  latent_dim: 256
  decoder_layers:
  - 512
  - 1024
  - 60664
  learning_rate: 0.0001
  predict_keys:
  - x_hat
  - z
  kl_weight: 1.0