# lightning.pytorch==2.2.5
model:
  class_path: sciml.models.MMVAEModel
  init_args:
    module:
      class_path: sciml.modules.MMVAE
      init_args:
        vae:
          class_path: sciml.modules.VAE
          init_args:
            n_in: 768
            encoder_layers:
            - 512
            - 256
            n_latent: 256
            decoder_layers:
            - 512
            n_out: 768
            distribution: ln
            encoder_kwargs: 
              dropout_rate:
              - 0.1
              - 0.0
              - 0.0
              use_layer_norm: true
            decoder_kwargs: {}
        experts:
          class_path: sciml.modules.base.Experts
          init_args:
            human_encoder_kwargs:
              layers:
              - 60664
              - 1024
              - 768
              dropout_rate: 0.1
              use_layer_norm: true
            human_decoder_kwargs:
              layers:
              - 768
              - 1024
              - 60664
            mouse_encoder_kwargs:
              layers:
              - 52417
              - 1024
              - 768
              dropout_rate: 0.1
              use_layer_norm: true
            mouse_decoder_kwargs:
              layers:
              - 768
              - 1024
              - 52417
    kl_annealing_fn: linear
    record_embeddings: false
    record_gradients: false
    configure_optimizer_kwargs: {}
    gradient_record_cap: 20