# lightning.pytorch==2.2.5
model:
  class_path: sciml.MMVAEModel
  init_args:
    mmvae:
      class_path: sciml.modules.MMVAE
      init_args:
        vae:
          class_path: sciml.modules.BasicVAE
          init_args:
            encoder_layers:
            - 768
            - 512
            - 256
            latent_dim: 256
            decoder_layers:
            - 512
            - 768
            use_he_init: true
        human_expert:
          class_path: sciml.modules.Expert
          init_args:
            encoder_layers:
            - 60664
            - 1024
            - 768
            decoder_layers:
            - 768
            - 1024
            - 60664
        mouse_expert:
          class_path: sciml.modules.Expert
          init_args:
            encoder_layers:
            - 52417
            - 1024
            - 768
            decoder_layers:
            - 768
            - 1024
            - 52417
    predict_keys:
    - x_hat
    - z
    kl_weight: 1
    plot_z_embeddings: false